name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-typecheck-test:
    runs-on: docker
    container:
      image: oven/bun:1
      env:
        NODE_TLS_REJECT_UNAUTHORIZED: "0"
    steps:
      - name: Install git
        run: apt-get update -qq && apt-get install -y -qq git > /dev/null
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
        env:
          GIT_SSL_NO_VERIFY: "true"
      - run: bun install --frozen-lockfile
      - run: bun run lint
      - run: bun run typecheck
      - run: bun run test

  build:
    runs-on: docker
    container:
      image: oven/bun:1
      env:
        NODE_TLS_REJECT_UNAUTHORIZED: "0"
    needs: lint-typecheck-test
    steps:
      - name: Install git
        run: apt-get update -qq && apt-get install -y -qq git > /dev/null
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
        env:
          GIT_SSL_NO_VERIFY: "true"
      - run: bun install --frozen-lockfile
      - run: bun run build
