apiVersion: v2
name: digarr
description: Music discovery app -- finds new artists based on your listening history
type: application
version: 0.1.1
appVersion: "0.1.1"

dependencies:
  - name: postgresql
    version: "16.4.3"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
