{{- if and .Values.podDisruptionBudget.enabled (gt (int .Values.replicaCount) 1) -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "digarr.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "digarr.labels" . | nindent 4 }}
    app.kubernetes.io/component: app
spec:
  {{- if .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- else if .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "digarr.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: app
{{- end }}
