{{- if .Values.backups.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "digarr.fullname" . }}-backups
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "digarr.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.backups.persistence.size | default "5Gi" }}
  {{- with .Values.backups.persistence.storageClass }}
  storageClassName: {{ . | quote }}
  {{- end }}
{{- end }}
