{{- if not .Values.database.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "digarr.fullname" . }}-db
  labels:
    {{- include "digarr.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.postgresql.enabled }}
  DATABASE_URL: {{ printf "postgresql://%s:%s@%s:%d/%s" .Values.postgresql.auth.username .Values.postgresql.auth.password (include "digarr.postgresHost" .) (int .Values.database.port) .Values.postgresql.auth.database | quote }}
  {{- else }}
  DATABASE_URL: {{ printf "postgresql://%s:%s@%s:%d/%s" .Values.database.user .Values.database.password .Values.database.host (int .Values.database.port) .Values.database.name | quote }}
  {{- end }}
{{- end }}
