import type { ServiceTestResult } from '@/core/types'
import { TRACKS_PER_ARTIST } from '../playlists/strategies/types'
import type { DestinationTarget, PlaylistItem, PlaylistResult } from './types'

const SPOTIFY_API = 'https://api.spotify.com'
const TRACKS_PER_BATCH = 100

export type SpotifyPlaylistConfig = {
  getAccessToken: () => Promise<string>
}

async function spotifyFetch<T>(
  accessToken: string,
  path: string,
  options?: { method?: string; body?: unknown },
): Promise<T> {
  const res = await fetch(`${SPOTIFY_API}${path}`, {
    method: options?.method ?? 'GET',
    headers: {
      Authorization: `Bearer ${accessToken}`,
      'Content-Type': 'application/json',
    },
    body: options?.body ? JSON.stringify(options.body) : undefined,
  })
  if (!res.ok) {
    const text = await res.text()
    throw new Error(`Spotify API ${res.status}: ${text}`)
  }
  return (await res.json()) as T
}

export function createSpotifyPlaylistTarget(
  targetId: number,
  config: SpotifyPlaylistConfig,
): DestinationTarget {
  return {
    id: `spotify-playlist-${targetId}`,
    name: 'Spotify Playlist',
    type: 'spotify-playlist',
    capabilities: ['createPlaylist'],

    async createPlaylist(
      name: string,
      items: PlaylistItem[],
      options?: { description?: string; public?: boolean; replace?: boolean },
    ): Promise<PlaylistResult> {
      try {
        const token = await config.getAccessToken()

        const me = await spotifyFetch<{ id: string }>(token, '/v1/me')

        // Search each artist and collect their top tracks
        const trackUris: string[] = []
        for (const item of items) {
          try {
            const search = await spotifyFetch<{
              artists: { items: Array<{ id: string; name: string; uri: string }> }
            }>(token, `/v1/search?q=${encodeURIComponent(item.artistName)}&type=artist&limit=1`)

            const artist = search.artists.items[0]
            if (!artist) continue

            const topTracks = await spotifyFetch<{
              tracks: Array<{ uri: string; name: string }>
            }>(token, `/v1/artists/${artist.id}/top-tracks?market=US`)

            for (const track of topTracks.tracks.slice(0, TRACKS_PER_ARTIST)) {
              trackUris.push(track.uri)
            }
          } catch {
            // Skip artists we can't find or fetch tracks for
          }
        }

        // Create playlist
        const playlist = await spotifyFetch<{
          id: string
          name: string
          external_urls: { spotify: string }
        }>(token, `/v1/users/${me.id}/playlists`, {
          method: 'POST',
          body: {
            name,
            description: options?.description ?? 'Generated by Digarr',
            public: options?.public ?? false,
          },
        })

        // Add tracks in batches of 100 (Spotify API limit)
        if (trackUris.length > 0) {
          for (let i = 0; i < trackUris.length; i += TRACKS_PER_BATCH) {
            const batch = trackUris.slice(i, i + TRACKS_PER_BATCH)
            await spotifyFetch(token, `/v1/playlists/${playlist.id}/tracks`, {
              method: 'POST',
              body: { uris: batch },
            })
          }
        }

        return {
          success: true,
          targetType: 'spotify-playlist',
          targetId,
          playlistId: playlist.id,
          playlistName: name,
          itemsAdded: trackUris.length,
        }
      } catch (err: unknown) {
        return {
          success: false,
          targetType: 'spotify-playlist',
          targetId,
          error: err instanceof Error ? err.message : String(err),
        }
      }
    },

    async testConnection(): Promise<ServiceTestResult> {
      try {
        const token = await config.getAccessToken()
        const me = await spotifyFetch<{ display_name: string }>(token, '/v1/me')
        return {
          success: true,
          message: `Connected as ${me.display_name}`,
        }
      } catch (err: unknown) {
        return {
          success: false,
          message: err instanceof Error ? err.message : String(err),
        }
      }
    },
  }
}
