// @vitest-environment node
import { afterEach, describe, expect, it, vi } from 'vitest'

const mockGetAccessToken = vi.fn().mockResolvedValue('mock-access-token')
const mockFetch = vi.fn()

vi.stubGlobal('fetch', mockFetch)

const { createSpotifyPlaylistTarget } = await import('@/core/targets/spotify-playlist')

function setupMockResponses() {
  mockFetch.mockImplementation(async (url: string | URL | Request, opts?: RequestInit) => {
    const urlStr = String(url)

    // GET /me -- current user
    if (urlStr.includes('/v1/me') && !urlStr.includes('/playlists')) {
      return new Response(JSON.stringify({ id: 'spotify-user-1', display_name: 'Test' }))
    }

    // GET /search -- artist search
    if (urlStr.includes('/v1/search')) {
      return new Response(
        JSON.stringify({
          artists: {
            items: [{ id: 'sp-ar-1', name: 'Radiohead', uri: 'spotify:artist:sp-ar-1' }],
          },
        }),
      )
    }

    // GET /artists/{id}/top-tracks
    if (urlStr.includes('/top-tracks')) {
      return new Response(
        JSON.stringify({
          tracks: [
            { id: 'sp-tr-1', uri: 'spotify:track:sp-tr-1', name: 'Creep' },
            { id: 'sp-tr-2', uri: 'spotify:track:sp-tr-2', name: 'Karma Police' },
          ],
        }),
      )
    }

    // POST /users/{id}/playlists -- create playlist
    if (urlStr.includes('/playlists') && opts?.method === 'POST' && !urlStr.includes('/tracks')) {
      return new Response(
        JSON.stringify({
          id: 'sp-pl-1',
          name: 'Digarr Discoveries',
          external_urls: { spotify: 'https://open.spotify.com/playlist/sp-pl-1' },
        }),
      )
    }

    // POST /playlists/{id}/tracks -- add tracks
    if (urlStr.includes('/tracks') && opts?.method === 'POST') {
      return new Response(JSON.stringify({ snapshot_id: 'snap-1' }))
    }

    return new Response('Not Found', { status: 404 })
  })
}

afterEach(() => {
  mockFetch.mockReset()
  mockGetAccessToken.mockReset().mockResolvedValue('mock-access-token')
})

describe('createSpotifyPlaylistTarget()', () => {
  it('has correct type and capabilities', () => {
    const target = createSpotifyPlaylistTarget(3, {
      getAccessToken: mockGetAccessToken,
    })
    expect(target.type).toBe('spotify-playlist')
    expect(target.capabilities).toContain('createPlaylist')
    expect(target.capabilities).not.toContain('addArtist')
    expect(target.capabilities).not.toContain('addToFavorites')
  })

  it('createPlaylist searches for artists and creates Spotify playlist', async () => {
    setupMockResponses()
    const target = createSpotifyPlaylistTarget(3, {
      getAccessToken: mockGetAccessToken,
    })

    const result = await target.createPlaylist?.(
      'Digarr Discoveries',
      [{ artistName: 'Radiohead', artistMbid: 'mbid-rh' }],
      { description: 'Auto-generated by Digarr' },
    )

    expect(result?.success).toBe(true)
    expect(result?.playlistId).toBe('sp-pl-1')
    expect(result?.itemsAdded).toBeGreaterThan(0)
    expect(mockGetAccessToken).toHaveBeenCalled()
  })

  it('createPlaylist sends Authorization header with token', async () => {
    setupMockResponses()
    const target = createSpotifyPlaylistTarget(3, {
      getAccessToken: mockGetAccessToken,
    })

    await target.createPlaylist?.('Test', [{ artistName: 'Radiohead', artistMbid: 'mbid-rh' }])

    // Every fetch call should have the Bearer token
    for (const call of mockFetch.mock.calls) {
      const opts = call[1] as RequestInit
      expect(opts.headers).toEqual(
        expect.objectContaining({ Authorization: 'Bearer mock-access-token' }),
      )
    }
  })

  it('createPlaylist batches tracks in groups of 100', async () => {
    // Each artist yields 3 top tracks. 40 artists * 3 = 120 tracks -> 2 batches
    let callCount = 0
    mockFetch.mockImplementation(async (url: string | URL | Request, opts?: RequestInit) => {
      const urlStr = String(url)
      if (urlStr.includes('/v1/me') && !urlStr.includes('/playlists')) {
        return new Response(JSON.stringify({ id: 'user-1', display_name: 'Test' }))
      }
      if (urlStr.includes('/v1/search')) {
        const n = callCount++
        return new Response(
          JSON.stringify({
            artists: {
              items: [{ id: `sp-ar-${n}`, name: `Artist ${n}`, uri: `spotify:artist:sp-ar-${n}` }],
            },
          }),
        )
      }
      if (urlStr.includes('/top-tracks')) {
        // Extract artist id from URL for unique track URIs
        const artistId = urlStr.match(/artists\/([^/]+)/)?.[1] ?? 'x'
        return new Response(
          JSON.stringify({
            tracks: [
              { uri: `spotify:track:${artistId}-1`, name: 'T1' },
              { uri: `spotify:track:${artistId}-2`, name: 'T2' },
              { uri: `spotify:track:${artistId}-3`, name: 'T3' },
            ],
          }),
        )
      }
      if (urlStr.includes('/playlists') && opts?.method === 'POST' && !urlStr.includes('/tracks')) {
        return new Response(
          JSON.stringify({ id: 'pl-1', name: 'Big', external_urls: { spotify: '' } }),
        )
      }
      if (urlStr.includes('/tracks') && opts?.method === 'POST') {
        return new Response(JSON.stringify({ snapshot_id: 'snap' }))
      }
      return new Response('Not Found', { status: 404 })
    })

    const artists = Array.from({ length: 40 }, (_, i) => ({
      artistName: `Artist ${i}`,
      artistMbid: `mbid-${i}`,
    }))

    const target = createSpotifyPlaylistTarget(1, {
      getAccessToken: mockGetAccessToken,
    })

    const result = await target.createPlaylist?.('Big Playlist', artists)

    expect(result?.success).toBe(true)
    expect(result?.itemsAdded).toBe(120)
    // 120 tracks -> 2 batches (100 + 20)
    const addTrackCalls = mockFetch.mock.calls.filter((call) => {
      const [url, opts] = call as [string, RequestInit | undefined]
      return url.includes('/tracks') && opts?.method === 'POST'
    })
    expect(addTrackCalls).toHaveLength(2)
  })

  it('createPlaylist returns failure when no access token', async () => {
    mockGetAccessToken.mockRejectedValueOnce(new Error('No Spotify OAuth token'))
    const target = createSpotifyPlaylistTarget(3, {
      getAccessToken: mockGetAccessToken,
    })

    const result = await target.createPlaylist?.('Test', [
      { artistName: 'Radiohead', artistMbid: 'mbid-rh' },
    ])

    expect(result?.success).toBe(false)
    expect(result?.error).toContain('No Spotify OAuth token')
  })

  it('createPlaylist skips artists not found on Spotify', async () => {
    mockFetch.mockImplementation(async (url: string | URL | Request, opts?: RequestInit) => {
      const urlStr = String(url)
      if (urlStr.includes('/v1/me') && !urlStr.includes('/playlists')) {
        return new Response(JSON.stringify({ id: 'user-1', display_name: 'Test' }))
      }
      if (urlStr.includes('/v1/search')) {
        return new Response(JSON.stringify({ artists: { items: [] } }))
      }
      if (urlStr.includes('/playlists') && opts?.method === 'POST' && !urlStr.includes('/tracks')) {
        return new Response(
          JSON.stringify({ id: 'pl-1', name: 'Test', external_urls: { spotify: '' } }),
        )
      }
      if (urlStr.includes('/tracks') && opts?.method === 'POST') {
        return new Response(JSON.stringify({ snapshot_id: 'snap' }))
      }
      return new Response('Not Found', { status: 404 })
    })

    const target = createSpotifyPlaylistTarget(1, {
      getAccessToken: mockGetAccessToken,
    })

    const result = await target.createPlaylist?.('Empty', [
      { artistName: 'Nonexistent Band', artistMbid: 'mbid-x' },
    ])

    expect(result?.success).toBe(true)
    expect(result?.itemsAdded).toBe(0)
  })

  it('testConnection validates the access token', async () => {
    setupMockResponses()
    const target = createSpotifyPlaylistTarget(3, {
      getAccessToken: mockGetAccessToken,
    })

    const result = await target.testConnection()
    expect(result.success).toBe(true)
    expect(result.message).toContain('Test')
  })

  it('testConnection returns failure on bad token', async () => {
    mockGetAccessToken.mockRejectedValueOnce(new Error('Token expired'))
    const target = createSpotifyPlaylistTarget(3, {
      getAccessToken: mockGetAccessToken,
    })

    const result = await target.testConnection()
    expect(result.success).toBe(false)
    expect(result.message).toContain('Token expired')
  })
})
