#!/usr/bin/env bash
# Regenerate deploy/k8s/rendered.yaml from the Helm chart so the raw
# manifest snapshot stays in lockstep with the chart. Run this any time
# deploy/helm/digarr/ changes, and commit the resulting diff. CI runs
# the same script and fails on a dirty working tree.
#
# Deterministic --set flags: pin release name, image tag, and the few
# required values so the output only changes when the chart changes.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CHART_DIR="${REPO_ROOT}/deploy/helm/digarr"
OUT_FILE="${REPO_ROOT}/deploy/k8s/rendered.yaml"

if ! command -v helm >/dev/null 2>&1; then
  echo "error: helm not found on PATH" >&2
  exit 1
fi

CHART_VERSION="$(awk '/^version:/ {print $2; exit}' "${CHART_DIR}/Chart.yaml")"

{
  cat <<HEADER
# SOURCE OF TRUTH: ${CHART_DIR#${REPO_ROOT}/}
# GENERATED BY: scripts/k8s-sync.sh (do not edit by hand)
# Chart version: ${CHART_VERSION}
#
# This file is a snapshot of \`helm template\` with default values plus
# the minimum required overrides. Real deployments should install the
# chart directly with \`helm install\`; this snapshot exists only so
# reviewers can see raw manifest shape without running helm locally.
HEADER
  helm template digarr "${CHART_DIR}" \
    --namespace digarr \
    --set postgresql.auth.password=REPLACE_ME
} > "${OUT_FILE}"

echo "wrote ${OUT_FILE#${REPO_ROOT}/} (chart ${CHART_VERSION})"
